name: Build for Android

on: [workflow_dispatch]

jobs:
  build:
    strategy:
      # max-parallel: 1
      matrix:
        # arch: ['arm' ,'arm64' ,'x86' ,'x64']
        arch: ['arm']
    runs-on: ubuntu-latest
    
    steps:
     

      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r22

      - name: Build swig
        run: |
          cd scripts
          python swigpp-java.py --profile standard --swig ../../mobile-swig/swig
      
      - name: Get branch name
        shell: bash
        run: echo "VERSION_NAME=$(echo ${GITHUB_HEAD_REF} | tr / - | sed "s/^[a-zA-Z]*-//g")" >> $GITHUB_ENV

      - name: Build CartoSDK
        run: |
          cd scripts
          python build-android.py --profile standard+valhalla --build-aar --build-version ${{ env.VERSION_NAME }} --configuration=Release

      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/android/*.zip
