name: Build for iOS

on: [workflow_dispatch]

env:
  CACHE_KEY_SUFFIX: v2

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - uses: actions/checkout@v2

      - name: Build swig
        run: |
          cd scripts
          python swigpp-objc.py --profile standard+valhalla --swig ../../mobile-swig/swig 
      
      - name: Get branch name
        shell: bash
        run: echo "VERSION_NAME=$(echo ${GITHUB_HEAD_REF} | tr / - | sed "s/^[a-zA-Z]*-//g")" >> $GITHUB_ENV

      - name: Build CartoSDK
        run: |
          cd scripts
          python build-ios.py --profile standard+valhalla --build-cocoapod --build-version ${{ env.VERSION_NAME }} --build-xcframework

      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/ios/*.zip